\copy department("id","department_name","priority","is_publish_vacancy","created_at","is_stopped","is_deleted") from ../../data/sample/department.csv with csv header;
\copy owner("id","owner_name","owner_kana","is_corporation","staff_id","created_at","created_user_id","updated_at","updated_user_id","is_stopped","is_deleted") from ../../data/sample/owner.csv with csv header;
\copy staff("id","department_id","first_name","last_name","priority","is_pm_staff","is_publish_vacancy","created_at","is_stopped","is_deleted") from ../../data/sample/staff.csv with csv header;
\copy trader("id","trader_group_id","trader_name","trader_kana","no_trading","no_portal","created_at","created_user_id","updated_at","updated_user_id","is_stopped","is_deleted") from ../../data/sample/trader.csv with csv header;
\copy trader_group("id","trader_group_name","trader_group_kana","created_at","created_user_id","updated_at","updated_user_id","is_stopped","is_deleted") from ../../data/sample/trader_group.csv with csv header;
\copy vacancy_input_bike_parking("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_bike_parking.csv with csv header;
\copy vacancy_input_cancel_notice("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_cancel_notice.csv with csv header;
\copy vacancy_input_change_lock("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_change_lock.csv with csv header;
\copy vacancy_input_cleaning("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_cleaning.csv with csv header;
\copy vacancy_input_document_price("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_document_price.csv with csv header;
\copy vacancy_input_electric("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_electric.csv with csv header;
\copy vacancy_input_garage("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_garage.csv with csv header;
\copy vacancy_input_gas("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_gas.csv with csv header;
\copy vacancy_input_guarantee("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_guarantee.csv with csv header;
\copy vacancy_input_guarantor_limit("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_guarantor_limit.csv with csv header;
\copy vacancy_input_insurance("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_insurance.csv with csv header;
\copy vacancy_input_internet("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_internet.csv with csv header;
\copy vacancy_input_payment("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_payment.csv with csv header;
\copy vacancy_input_portal("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_portal.csv with csv header;
\copy vacancy_input_renewal_charge("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_renewal_charge.csv with csv header;
\copy vacancy_input_short_cancel("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_short_cancel.csv with csv header;
\copy vacancy_input_water("input_contents","priority","created_at","is_stopped") from ../../data/sample/vacancy_input_water.csv with csv header;
\copy vacancy_theme("name","title","description","priority","room_auth_level_id","is_publish","created_at","is_stopped") from ../../data/sample/vacancy_theme.csv with csv header;
alter sequence company_id_seq restart with 2;
alter sequence department_id_seq restart with 2;
alter sequence staff_id_seq restart with 2;
alter sequence vacancy_input_bike_parking_id_seq restart with 2;
alter sequence vacancy_input_cancel_notice_id_seq restart with 4;
alter sequence vacancy_input_change_lock_id_seq restart with 2;
alter sequence vacancy_input_cleaning_id_seq restart with 2;
alter sequence vacancy_input_document_price_id_seq restart with 2;
alter sequence vacancy_input_electric_id_seq restart with 2;
alter sequence vacancy_input_garage_id_seq restart with 3;
alter sequence vacancy_input_gas_id_seq restart with 2;
alter sequence vacancy_input_guarantee_id_seq restart with 2;
alter sequence vacancy_input_guarantor_limit_id_seq restart with 2;
alter sequence vacancy_input_insurance_id_seq restart with 2;
alter sequence vacancy_input_internet_id_seq restart with 3;
alter sequence vacancy_input_payment_id_seq restart with 3;
alter sequence vacancy_input_portal_id_seq restart with 3;
alter sequence vacancy_input_renewal_charge_id_seq restart with 2;
alter sequence vacancy_input_short_cancel_id_seq restart with 2;
alter sequence vacancy_input_water_id_seq restart with 3;
alter sequence vacancy_theme_id_seq restart with 2;
